#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""CI gate: verify the in-app qBittorrent preferences editor implements the
COMPLETE set of qBittorrent-Enhanced WebUI Options keys.

The reference list `config/qb_enhanced_prefs_required.txt` holds every
preference key that the bundled engine (pinned ref in
.github/workflows/android.yml, QBT_REF) both serializes in
AppController::preferencesAction() (GET /api/v2/app/preferences) and accepts
in AppController::setPreferencesAction() (POST setPreferences) — i.e. every
key that is round-trippable over the WebUI Options API.

The editor is schema-driven (ui/qbsettings/QBPrefSchema.kt, generated by
scripts/gen_qbprefs_schema.py from scripts/qbprefs_schema_data.py). Keys the
schema does not know are still rendered at runtime via QBPrefSchema.inferField
(the dynamic "other" section), so unknown keys never break the editor — but
every KNOWN engine key must appear in the schema so it gets a proper label,
section and control. This script fails the build when any required key is
missing from the schema.

Regenerating the reference list when QBT_REF changes:
    git clone https://github.com/c0re100/qBittorrent-Enhanced-Edition
    python3 - <<'EOF'
    import re
    src = open('qBittorrent-Enhanced-Edition/src/webui/api/appcontroller.cpp').read()
    g = src.index('void AppController::preferencesAction()')
    s = src.index('void AppController::setPreferencesAction()')
    get = set(re.findall(r'data\[u"([A-Za-z_0-9]+)"_s\]', src[g:s]))
    put = set(re.findall(r'hasKey\(u"([A-Za-z_0-9]+)"_s\)', src[s:]))
    open('config/qb_enhanced_prefs_required.txt', 'w').write(
        '\n'.join(sorted(get & put)) + '\n')
    EOF
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "app/src/main/java/io/github/xixka/qbittorrent/ui/qbsettings/QBPrefSchema.kt"
REQUIRED_FILE = ROOT / "config/qb_enhanced_prefs_required.txt"


def schema_keys() -> set:
    """Preference keys the schema table renders with a dedicated field()."""
    src = SCHEMA.read_text(encoding="utf-8")
    return set(re.findall(r'field\(\s*"([A-Za-z_0-9]+)"', src))


def required_keys() -> set:
    return {line.strip() for line in REQUIRED_FILE.read_text().splitlines() if line.strip()}


# Keys intentionally NOT exposed by the in-app editor because the app OWNS
# and force-manages them: NoxConfig re-applies the app's own value at every
# engine start, so a user edit in the editor would be silently reverted on
# the next restart — showing a control that snaps back is worse than not
# showing it. Every key here MUST have a matching justification comment and
# a matching comment in QBPrefSchema.kt.
APP_MANAGED = {
    # qB's "bypass authentication for whitelisted subnets" pair: LAN
    # clients must always log in (round-17 requirement) — the switch is
    # kept off and re-patched off by NoxConfig.patchConfig, so neither
    # the toggle nor the subnet list is user-editable in-app.
    "bypass_auth_subnet_whitelist_enabled",
    "bypass_auth_subnet_whitelist",
}


def main() -> int:
    if not SCHEMA.exists():
        print(f"FATAL: missing {SCHEMA}")
        return 2
    written = schema_keys()
    required = required_keys()
    if not required:
        print(f"FATAL: empty/missing {REQUIRED_FILE}")
        return 2

    missing = sorted(required - written - APP_MANAGED)
    print(f"preference keys in the schema: {len(written)}")
    print(f"required engine keys ({REQUIRED_FILE.name}): {len(required)}")
    print(f"app-managed keys (owned by NoxConfig, hidden on purpose): {len(APP_MANAGED)}")
    for k in sorted(APP_MANAGED & required):
        print(f"    - {k}")

    if missing:
        print("\nMISSING preference keys (qBittorrent Enhanced config the "
              "dynamic editor has no schema entry for):")
        for k in missing:
            print(f"  - {k}")
        return 1

    print("OK: the dynamic settings editor schema covers the complete "
          "qBittorrent Enhanced WebUI Options key set (unknown future keys "
          "are handled generically at runtime; app-managed keys are "
          "enforced by NoxConfig instead).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
